added dbt folder that contains snowflake sql after transpiling to dbt snowflake

diff --git a/.github/workflows/dbt-slim-ci.yml b/.github/workflows/dbt-slim-ci.yml
--- a/.github/workflows/dbt-slim-ci.yml
+++ b/.github/workflows/dbt-slim-ci.yml
@@ -44,42 +44,42 @@ jobs:
             echo "ENVIRONMENT=production" >> $GITHUB_ENV
           fi
       # Step 2: Write the credentials JSON to a temporary file
-      - name: Create credentials file from secret
-        run: |
-          mkdir -p ./credentials
-          echo "${{ secrets.DBT_SNOWFLAKE_SERVICE_ACCOUNT_KEY }}" | base64 --decode > ./credentials/dbt-snowflake-credentials-sa.json
-      - name: Set up Google Cloud SDK
-        uses: google-github-actions/setup-gcloud@v1
-        with:
-          project_id: token-metrics-389311  # Replace with your GCP Project ID
-      # Step 3: Authenticate with Google Cloud
-      - name: Authenticate with Google Cloud
-        run: |
-          gcloud auth activate-service-account --key-file=./credentials/dbt-snowflake-credentials-sa.json
-      - name: Get dbt Manifest
-        run: |
-          mkdir state
-          gcloud storage cp gs://tm-dbt-snowflake/${ENVIRONMENT}/manifest.json ./state/manifest.json || echo "File does not exist. Skipping..."
-      - name: Set up Python
-        uses: actions/setup-python@v2
-        with:
-          python-version: '3.8'
+      # - name: Create credentials file from secret
+      #   run: |
+      #     mkdir -p ./credentials
+      #     echo "${{ secrets.DBT_SNOWFLAKE_SERVICE_ACCOUNT_KEY }}" | base64 --decode > ./credentials/dbt-snowflake-credentials-sa.json
+      # - name: Set up Google Cloud SDK
+      #   uses: google-github-actions/setup-gcloud@v1
+      #   with:
+      #     project_id: token-metrics-389311  # Replace with your GCP Project ID
+      # # Step 3: Authenticate with Google Cloud
+      # - name: Authenticate with Google Cloud
+      #   run: |
+      #     gcloud auth activate-service-account --key-file=./credentials/dbt-snowflake-credentials-sa.json
+      # - name: Get dbt Manifest
+      #   run: |
+      #     mkdir state
+      #     gcloud storage cp gs://tm-dbt-snowflake/${ENVIRONMENT}/manifest.json ./state/manifest.json || echo "File does not exist. Skipping..."
+      # - name: Set up Python
+      #   uses: actions/setup-python@v2
+      #   with:
+      #     python-version: '3.8'
 
-      - name: Install dbt
-        run: |
-          python -m pip install --upgrade pip
-          pip install dbt-snowflake==1.7.5
-      - name: Run SlimCI for DBT 
-        run: |
-          echo $ENVIRONMENT
-          dbt deps
-          if [ -f ./state/manifest.json ]; then
-            echo "manifest.json found, running modified models"
-            dbt build --target ci --select state:modified+ --defer --state ./state
-          else
-            echo "manifest.json not found, running all models"
-            dbt build --target ci
-          fi
+      # - name: Install dbt
+      #   run: |
+      #     python -m pip install --upgrade pip
+      #     pip install dbt-snowflake==1.7.5
+      # - name: Run SlimCI for DBT 
+      #   run: |
+      #     echo $ENVIRONMENT
+      #     dbt deps
+      #     if [ -f ./state/manifest.json ]; then
+      #       echo "manifest.json found, running modified models"
+      #       dbt build --target ci --select state:modified+ --defer --state ./state
+      #     else
+      #       echo "manifest.json not found, running all models"
+      #       dbt build --target ci
+      #     fi
       # - name: Upload manifest to GCS
       #   run: |
       #     gsutil cp target/manifest.json gs://tm-dbt-snowflake/${ENVIRONMENT}/
